<<<<<<< HEAD
name: Flutter CI and Release
=======
name: Flutter CI
>>>>>>> 7eb0a1ea (disable Signing)

# 创建触发打包条件：只要推送 tag，就会触发版本打包
on:
  push:
    tags:
      - v*

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the repository
    - uses: actions/checkout@v1
      with:
        path: office
    
    # Setup Java environment in order to build the Android app.
    - uses: actions/setup-java@v1
      with:
        java-version: '17.x'
    
    # Setup the Flutter environment.
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
    
    # Get Flutter dependencies.
    - run: flutter pub get
    
    # Build APK using debug signature
    - run: flutter build apk --release --target-platform android-arm --no-shrink
    
    # Release APK
    - name: Release apk
      uses: ncipollo/release-action@v1.5.0
      with:
        artifacts: "build/app/outputs/apk/release/*.apk"
<<<<<<< HEAD
        token: ${{ secrets.GITHUB_TOKEN }}
=======
        token: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 7eb0a1ea (disable Signing)
